# Auto Scout Project

**Author:** Mark Joslin

**GitHub:** [link](https://github.com/mjoslin-ai/Magnimind-Project-Auto-Scout)

**Phase 2:** Missing Value Analysis

## Table of Contents

* Objective
* Libraries
* Import Data
* Missing Value Analysis
* Export Data

## Objective

Clean and preprocess a 2019 online vehicle dataset (≈15,919 rows, 54 columns, 9 car models) containing many inconsistent, broken, and messy values, so it becomes suitable for machine learning. The project is broken up into four main phases: 

1. Data Cleaning: 
    * Removing broken, irrelevant, or redundant columns
    * Creating new columns with clean, meaningful, and usable values
2. Missing Value Analysis:
    * Filling in the gabs where data is missing
    * With techniques such as mean, median, or mode
3. Outlier Analysis:
    * Outliers are detected and visualized using boxplots and histograms.
    * Rather than removing all outliers (since extreme but valid values are expected for certain car models, e.g. luxury vehicles with high prices or powerful engines), the focus is on identifying and addressing only clear misprints or logically inconsistent entries.
4. Dummy Variable Analysis:
    * Categorical and multi-label columns (e.g. Comfort_Convenience, Extras) are converted to numeric format to create binary indicator variables suitable for machine learning.
    * Key techniques include pd.get_dummies() and str.get_dummies(sep=",")

This notebook covers Phase 2 Missing Value Analysis with input from phase1_cleaned_data.csv (15919 rows, 34 columns) and output phase2_cleaned_data.csv.

## Libraries

In [46]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore", category=SyntaxWarning)

## Import Data

In [47]:
df_org = pd.read_csv("data/phase1_cleaned_data.csv")
df = df_org.copy()
df.head(3).T

,0,1,2
make_model,Audi A1,Audi A1,Audi A1
body_type,Sedans,Sedans,Sedans
price,15770,14500,14640
vat,VAT deductible,Price negotiable,VAT deductible
km,56013.0,80000.0,83450.0
previous_owners,2.0,NaN,1.0
next_inspection,2021-06,NaN,NaN
inspection_new,Yes,NaN,NaN
body_color,Black,Red,Black
paint_type,metallic,NaN,metallic
nr_of_doors,5.0,3.0,4.0
nr_of_seats,5.0,4.0,4.0
gearing_type,Automatic,Automatic,Automatic
cylinders,3.0,4.0,NaN
drive_chain,front,front,front
fuel,Diesel,Benzine,Diesel
emission_class,Euro 6,Euro 6,Euro 6
comfort_convenience,"Air conditioning,Armrest,Automatic climate con...","Air conditioning,Automatic climate control,Hil...","Air conditioning,Cruise control,Electrical sid..."
entertainment_media,"Bluetooth,Hands-free equipment,On-board comput...","Bluetooth,Hands-free equipment,On-board comput...","MP3,On-board computer"
extras,"Alloy wheels,Catalytic Converter,Voice Control","Alloy wheels,Sport seats,Sport suspension,Voic...","Alloy wheels,Voice Control"
safety_security,"ABS,Central door lock,Daytime running lights,D...","ABS,Central door lock,Central door lock with r...","ABS,Central door lock,Daytime running lights,D..."
gears,NaN,7.0,NaN
displacement_cc,1422.0,1798.0,1598.0
age_years,3.0,2.0,3.0
first_registered_month,1.0,3.0,2.0
hp_kw,66.0,141.0,85.0
condition,Used,Used,Used
warranty_months,NaN,NaN,NaN
upholstery_type,Cloth,Cloth,Cloth
upholstery_color,Black,Grey,Black
weight_kg,1220.0,1255.0,NaN
combined_l_per_100km,3.8,5.6,3.8
city_l_per_100km,4.3,7.1,4.4
country_l_per_100km,3.5,4.7,3.4
emissions_g_co2/km,99.0,129.0,99.0

In [48]:
missing_df = df.isnull().sum().reset_index()
missing_df.columns = ['column', 'missing_count']
missing_df = missing_df[missing_df['missing_count'] > 0].reset_index(drop=True)
print(missing_df)

                    column  missing_count
0                body_type             60
1                      vat           4513
2                       km           1024
3          previous_owners           6640
4          next_inspection          12384
5           inspection_new          11987
6               body_color            597
7               paint_type           5772
8              nr_of_doors            212
9              nr_of_seats            977
10               cylinders           5680
11             drive_chain           6858
12          emission_class           3628
13     comfort_convenience            920
14     entertainment_media           1374
15                  extras           2962
16         safety_security            982
17                   gears           4712
18         displacement_cc            213
19               age_years           1597
20  first_registered_month           1597
21                   hp_kw             88
22               condition              2
23         warranty_months          11066
24         upholstery_type           4871
25        upholstery_color           6821
26               weight_kg           6974
27    combined_l_per_100km           2033
28        city_l_per_100km           2436
29     country_l_per_100km           2376
30      emissions_g_co2/km           2436

## Missing Value Analysis

### body_type

In [49]:
df['body_type'].value_counts(dropna=False)

body_type
Sedans           7903
Station wagon    3553
Compact          3153
Van               783
Other             290
Transporter        88
NaN                60
Off-Road           56
Coupe              25
Convertible         8
Name: count, dtype: int64

In [50]:
df['body_type'] = df['body_type'].replace("Other", np.nan)

In [51]:
bt = df['body_type'].fillna(df.groupby('make_model')['body_type'].transform(lambda x: x.mode()[0]))

In [52]:
bt.value_counts(dropna=False)

body_type
Sedans           8005
Station wagon    3678
Compact          3242
Van               817
Transporter        88
Off-Road           56
Coupe              25
Convertible         8
Name: count, dtype: int64

In [53]:
df['body_type'] = bt

### condition

In [54]:
df['condition'].value_counts(dropna=False)

condition
Used              11096
New                1650
Pre-registered     1364
Employee's car     1011
Demonstration       796
NaN                   2
Name: count, dtype: int64

In [55]:
c = df['condition'].fillna(df.groupby(['make_model', 'price'])['condition'].transform(lambda x: x.mode()[0] if not x.mode().empty else pd.NA))

In [56]:
c.value_counts(dropna=False)

condition
Used              11097
New                1651
Pre-registered     1364
Employee's car     1011
Demonstration       796
Name: count, dtype: int64

In [57]:
df['condition'] = c

### vat

In [58]:
df['vat'].value_counts(dropna=False)

vat
VAT deductible      10980
NaN                  4513
Price negotiable      426
Name: count, dtype: int64

In [59]:
v = df['vat'].fillna('VAT nondeductible')

In [60]:
v.value_counts(dropna=False)

vat
VAT deductible       10980
VAT nondeductible     4513
Price negotiable       426
Name: count, dtype: int64

In [61]:
df['vat'] = v

### age_years

In [62]:
df['age_years'].value_counts(dropna=False)

age_years
1.0    4522
3.0    3674
2.0    3273
0.0    2853
NaN    1597
Name: count, dtype: int64

In [63]:
df.groupby("age_years")['km'].describe()

,count,mean,std,min,25%,50%,75%,max
age_years,,,,,,,,
0.0,2706.0,2085.355137,5365.880693,1.0,10.00,50.0,3000.0,127022.0
1.0,4484.0,18035.239072,11052.524314,1.0,9990.00,17872.0,25078.5,136000.0
2.0,3272.0,41754.940709,28295.747886,1.0,21541.75,34752.0,54805.5,317000.0
3.0,3674.0,77442.520958,39170.142977,10.0,48000.00,72914.5,99950.0,291800.0

In [64]:
df['age_years'] = df['age_years'].fillna(
    pd.cut(
        df['km'],
        bins=[-np.inf, 10000, 28000, 50000, np.inf],
        labels=[0, 1, 2, 3],
        right=False
    )
)

In [65]:
df['age_years'].value_counts(dropna=False)

age_years
1.0    4528
3.0    3679
0.0    3597
2.0    3277
NaN     838
Name: count, dtype: int64

In [66]:
df[df['age_years'].isna()]['condition'].value_counts(dropna=False)

condition
New               835
Pre-registered      1
Employee's car      1
Used                1
Name: count, dtype: int64

In [67]:
df['age_years'] = df['age_years'].fillna(0)

In [68]:
df['age_years'].value_counts(dropna=False)

age_years
1.0    4528
0.0    4435
3.0    3679
2.0    3277
Name: count, dtype: int64

### km

In [69]:
df['km'].value_counts(dropna=False)

km
10.0      1045
NaN       1024
1.0        367
5.0        170
50.0       148
          ...
3353.0       1
2860.0       1
2864.0       1
1506.0       1
57.0         1
Name: count, Length: 6690, dtype: int64

Group by make_model, body_type, and age_years, and fill NaNs with median value

In [70]:
k = df['km'].fillna(df.groupby(['price', 'condition', 'age_years'])['km'].transform(lambda x: x.median()))

In [71]:
k.isna().sum()

np.int64(719)

In [72]:
k = k.fillna(df.groupby(['price', 'age_years'])['km'].transform(lambda x: x.median()))

In [73]:
k.isna().sum()

np.int64(505)

In [74]:
k = k.fillna(df.groupby(['age_years'])['km'].transform(lambda x: x.median()))

In [75]:
k.isna().sum()

np.int64(0)

In [76]:
k.value_counts(dropna=False)

km
10.0      1151
14.0       504
1.0        423
5.0        183
50.0       180
          ...
3353.0       1
2860.0       1
2864.0       1
1506.0       1
57.0         1
Name: count, Length: 6734, dtype: int64

In [77]:
df['km'] = k

### previous_owners

In [78]:
df['previous_owners'].value_counts(dropna=False)

previous_owners
1.0    8294
NaN    6640
2.0     778
0.0     188
3.0      17
4.0       2
Name: count, dtype: int64

In [79]:
df.loc[df['previous_owners'].isna(), ['condition', 'age_years']].value_counts(dropna=False)

condition       age_years
New             0.0          1470
Used            3.0          1224
                2.0          1177
                1.0          1157
Pre-registered  0.0           454
Used            0.0           453
Demonstration   0.0           241
Employee's car  1.0           221
                2.0            71
Pre-registered  1.0            62
Employee's car  0.0            56
Demonstration   1.0            35
Employee's car  3.0             8
Demonstration   2.0             5
Pre-registered  2.0             3
New             1.0             2
Demonstration   3.0             1
Name: count, dtype: int64

In [80]:
po = df['previous_owners'].fillna(df.groupby(['condition', 'age_years', 'price'])['previous_owners'].transform(lambda x: x.mode()[0] if not x.mode().empty else np.nan))

In [81]:
po.isna().sum()

np.int64(3156)

In [82]:
po = po.fillna(df.groupby(['condition', 'age_years'])['previous_owners'].transform(lambda x: x.mode()[0] if not x.mode().empty else np.nan))

In [83]:
po.isna().sum()

np.int64(0)

In [84]:
po.value_counts(dropna=False)

previous_owners
1.0    13356
0.0     1660
2.0      882
3.0       19
4.0        2
Name: count, dtype: int64

In [85]:
df['previous_owners'] = po

### next_inspection

In [86]:
df['next_inspection'].value_counts(dropna=False)

next_inspection
NaN        12384
2021-06      471
2021-03      210
2021-05      180
2021-04      171
           ...
2017-12        1
2022-12        1
1921-01        1
2024-03        1
2022-11        1
Name: count, Length: 78, dtype: int64

In [87]:
df.loc[df['next_inspection'].isna(), 'age_years'].value_counts(dropna=False)

age_years
0.0    3592
1.0    3313
3.0    2889
2.0    2590
Name: count, dtype: int64

In EU, next inspection follows the periodic technical inspections (PTI) of vehicles 4 years after first registration

In [88]:
frm = df['first_registered_month']

In [89]:
frm.value_counts(dropna=False)

first_registered_month
3.0     2245
2.0     1964
4.0     1959
5.0     1875
1.0     1734
6.0     1617
NaN     1597
7.0      793
8.0      494
9.0      436
11.0     433
10.0     411
12.0     361
Name: count, dtype: int64

In [90]:
frm = frm.fillna(df.groupby(['age_years', 'make_model'])['first_registered_month'].transform(lambda x: x.mode()[0]))

In [91]:
frm = frm.astype('Int64').astype(str).str.zfill(2)

In [92]:
df['next_inspection'].fillna((2019 - df['age_years'] + 4).round(0).astype(int).astype(str) + '-' + frm)

0        2021-06
1        2021-03
2        2020-02
3        2020-08
4        2020-05
          ...
15914    2023-03
15915    2022-01
15916    2023-03
15917    2023-06
15918    2023-01
Name: next_inspection, Length: 15919, dtype: str

In [93]:
ni = df['next_inspection'].fillna((2019 - df['age_years'] + 4).round(0).astype(int).astype(str) + '-' + frm)

ni = pd.to_datetime(ni, errors='coerce').dt.to_period('M')

In [94]:
ni.isna().sum()

np.int64(0)

In [95]:
ni.value_counts(dropna=False)

next_inspection
2023-04    837
2021-06    823
2023-03    767
2023-02    740
2022-03    661
          ...
2017-12      1
2023-08      1
2023-11      1
1921-01      1
2024-03      1
Freq: M, Name: count, Length: 83, dtype: int64

In [96]:
df['next_inspection'] = ni
df.drop(columns=['first_registered_month'], inplace=True)

### inspection_new

In [97]:
df['inspection_new'].value_counts(dropna=False)

inspection_new
NaN    11987
Yes     3932
Name: count, dtype: int64

In [98]:
df['inspection_new'] = df['inspection_new'].fillna('No')

### body_color

In [99]:
df['body_color'].value_counts(dropna=False)

body_color
Black     3745
Grey      3505
White     3406
Silver    1647
Blue      1431
Red        957
NaN        597
Brown      289
Green      154
Beige      108
Yellow      51
Violet      18
Bronze       6
Orange       3
Gold         2
Name: count, dtype: int64

In [100]:
bc = df['body_color'].fillna(df.groupby(['make_model', 'body_type'])['body_color'].transform(lambda x: x.mode()[0] if not x.mode().empty else df['body_color'].mode()[0]))

In [101]:
bc.value_counts(dropna=False)

body_color
Black     3946
Grey      3834
White     3469
Silver    1647
Blue      1431
Red        957
Brown      289
Green      158
Beige      108
Yellow      51
Violet      18
Bronze       6
Orange       3
Gold         2
Name: count, dtype: int64

In [102]:
df['body_color'] = bc

### paint_type

In [103]:
df['paint_type'].value_counts(dropna=False)

paint_type
metallic       9794
NaN            5772
uni/basic       347
perl effect       6
Name: count, dtype: int64

In [104]:
df.loc[df['paint_type'].isna(), ['make_model', 'body_type']].value_counts(dropna=False)

make_model      body_type
Audi A3         Sedans           1018
Renault Clio    Sedans            531
Opel Corsa      Compact           506
Audi A1         Sedans            493
Opel Insignia   Station wagon     473
Opel Astra      Station wagon     364
Opel Corsa      Sedans            358
Opel Astra      Sedans            333
Audi A1         Compact           311
Opel Insignia   Sedans            310
Renault Espace  Van               293
Renault Clio    Compact           201
                Station wagon     164
Audi A3         Station wagon     113
Opel Astra      Compact            87
Audi A3         Compact            73
Renault Espace  Station wagon      28
Renault Clio    Transporter        26
Renault Espace  Transporter        18
Renault Duster  Off-Road           17
Opel Corsa      Coupe               9
Renault Espace  Sedans              7
Opel Insignia   Compact             6
Opel Corsa      Transporter         5
Opel Insignia   Off-Road            5
Audi A1         Station wagon       4
Audi A3         Convertible         4
Opel Corsa      Off-Road            3
Renault Espace  Compact             3
Opel Corsa      Van                 2
Renault Clio    Van                 2
Renault Espace  Coupe               2
Opel Astra      Coupe               1
Opel Insignia   Coupe               1
Renault Clio    Coupe               1
Name: count, dtype: int64

In [105]:
pt = df['paint_type'].fillna(df.groupby(['make_model', 'body_type'])['paint_type'].transform(lambda x: x.mode()[0] if not x.mode().empty else pd.NA))

In [106]:
pt.isna().sum()

np.int64(11)

In [107]:
pt = pt.fillna(df.groupby(['make_model'])['paint_type'].transform(lambda x: x.mode()[0] if not x.mode().empty else pd.NA))

In [108]:
pt.isna().sum()

np.int64(0)

In [109]:
pt.value_counts(dropna=False)

paint_type
metallic       15523
uni/basic        390
perl effect        6
Name: count, dtype: int64

In [110]:
df['paint_type'] = pt

### nr_of_doors

In [111]:
df['nr_of_doors'].value_counts(dropna=False)

nr_of_doors
5.0    11575
4.0     3079
3.0      832
2.0      219
NaN      212
1.0        1
7.0        1
Name: count, dtype: int64

In [112]:
nod = df['nr_of_doors'].fillna(df.groupby(['body_type'])['nr_of_doors'].transform(lambda x: x.mode()[0] if not x.mode().empty else pd.NA))

In [113]:
nod.isna().sum()

np.int64(0)

In [114]:
df['nr_of_doors'] = nod

### nr_of_seats

In [115]:
df['nr_of_seats'].value_counts(dropna=False)

nr_of_seats
5.0    13336
4.0     1125
NaN      977
7.0      362
2.0      116
6.0        2
3.0        1
Name: count, dtype: int64

In [116]:
nos = df['nr_of_seats'].fillna(df.groupby(['body_type', 'make_model'])['nr_of_seats'].transform(lambda x: x.mode()[0] if not x.mode().empty else pd.NA))

In [117]:
nos.isna().sum()

np.int64(6)

In [118]:
nos = nos.fillna(df.groupby(['body_type'])['nr_of_seats'].transform(lambda x: x.mode()[0] if not x.mode().empty else pd.NA))

In [119]:
nos.isna().sum()

np.int64(0)

In [120]:
df['nr_of_seats'] = nos

### cylinders

In [121]:
df['cylinders'].value_counts(dropna=False)

cylinders
4.0    8105
NaN    5680
3.0    2104
5.0      22
6.0       3
8.0       2
2.0       2
1.0       1
Name: count, dtype: int64

In [122]:
cy = df['cylinders'].fillna(df.groupby(['make_model', 'body_type'])['cylinders'].transform(lambda x: x.mode()[0] if not x.mode().empty else pd.NA))

In [123]:
cy.isna().sum()

np.int64(7)

In [124]:
cy = cy.fillna(df.groupby(['make_model'])['cylinders'].transform(lambda x: x.mode()[0] if not x.mode().empty else pd.NA))

In [125]:
cy.isna().sum()

np.int64(1)

In [126]:
cy = cy.fillna(cy.mode()[0])

In [127]:
df['cylinders'] = cy

### drive_chain

In [128]:
df['drive_chain'].value_counts(dropna=False)

drive_chain
front    8886
NaN      6858
4WD       171
rear        4
Name: count, dtype: int64

In [129]:
dc = df['drive_chain'].fillna(df.groupby(['make_model', 'body_type'])['drive_chain'].transform(lambda x: x.mode()[0] if not x.mode().empty else pd.NA))

In [130]:
dc.isna().sum()

np.int64(12)

In [131]:
dc = dc.fillna(df.groupby(['make_model'])['drive_chain'].transform(lambda x: x.mode()[0] if not x.mode().empty else pd.NA))

In [132]:
dc.isna().sum()

np.int64(0)

In [133]:
df['drive_chain'] = dc

### emission_class

In [134]:
df['emission_class'].value_counts(dropna=False)

emission_class
Euro 6    12173
NaN        3628
Euro 5       78
Euro 4       40
Name: count, dtype: int64

In [135]:
ec = df['emission_class'].fillna(df.groupby(['fuel', 'make_model', 'body_type', 'displacement_cc'])['emission_class'].transform(lambda x: x.mode()[0] if not x.mode().empty else pd.NA))

In [136]:
ec.isna().sum()

np.int64(348)

In [137]:
ec = ec.fillna(df.groupby(['fuel', 'make_model', 'body_type'])['emission_class'].transform(lambda x: x.mode()[0] if not x.mode().empty else pd.NA))

In [138]:
ec.isna().sum()

np.int64(13)

In [139]:
ec = ec.fillna(df.groupby(['make_model', 'body_type'])['emission_class'].transform(lambda x: x.mode()[0] if not x.mode().empty else pd.NA))

In [140]:
ec.isna().sum()

np.int64(9)

In [141]:
ec = ec.fillna(df.groupby(['make_model'])['emission_class'].transform(lambda x: x.mode()[0] if not x.mode().empty else pd.NA))

In [142]:
ec.isna().sum()

np.int64(0)

In [143]:
df['emission_class'] = ec

### comfort_convenience

In [144]:
df['comfort_convenience'].value_counts(dropna=False)

comfort_convenience
NaN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  920
Air conditioning,Electrical side mirrors,Hill Holder,Power windows                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   216
Air conditioning,Electrical side mirrors,Power windows                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               134
Air conditioning,Power windows                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       130
Air conditioning,Armrest,Automatic climate control,Cruise control,Electrical side mirrors,Leather steering wheel,Light sensor,Lumbar support,Multi-function steering wheel,Navigation system,Park Distance Control,Parking assist system sensors front,Parking assist system sensors rear,Power windows,Rain sensor,Seat heating,Start-stop system                                                                                                                                                                                                                   105
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ...
Air conditioning,Automatic climate control,Cruise control,Electrically heated windshield,Electric tailgate,Keyless central door lock,Leather steering wheel,Light sensor,Lumbar support,Multi-function steering wheel,Navigation system,Panorama roof,Park Distance Control,Power windows,Rain sensor,Seat heating,Start-stop system                                                                                                                                                                                                                                   1
Air conditioning,Automatic climate control,Cruise control,Electrically adjustable seats,Electrical side mirrors,Light sensor,Multi-function steering wheel,Navigation system,Panorama roof,Park Distance Control,Parking assist system camera,Parking assist system self-steering,Parking assist system sensors front,Parking assist system sensors rear,Power windows,Rain sensor,Seat heating,Start-stop system,Sunroof                                                                                                                                              1
Air conditioning,Armrest,Automatic climate control,Cruise control,Electrically adjustable seats,Electrically heated windshield,Electrical side mirrors,Electric tailgate,Heads-up display,Heated steering wheel,Hill Holder,Keyless central door lock,Leather steering wheel,Light sensor,Lumbar support,Multi-function steering wheel,Navigation system,Panorama roof,Park Distance Control,Parking assist system camera,Parking assist system sensors front,Parking assist system sensors rear,Power windows,Rain sensor,Seat heating,Start-stop system,Sunroof      1
Air conditioning,Armrest,Automatic climate control,Cruise control,Electrically adjustable seats,Electrically heated windshield,Electrical side mirrors,Electric tailgate,Heads-up display,Heated steering wheel,Keyless central door lock,Leather steering wheel,Light sensor,Lumbar support,Massage seats,Multi-function steering wheel,Navigation system,Panorama roof,Park Distance Control,Parking assist system camera,Parking assist system sensors front,Parking assist system sensors rear,Power windows,Rain sensor,Seat heating,Start-stop system            1
Air conditioning,Automatic climate control,Cruise control,Electrically heated windshield,Electrical side mirrors,Electric tailgate,Heads-up display,Heated steering wheel,Hill Holder,Keyless central door lock,Leather steering wheel,Light sensor,Lumbar support,Navigation system,Park Distance Control,Parking assist system camera,Parking assist system self-steering,Parking assist system sensors front,Parking assist system sensors rear,Power windows,Rain sensor,Seat heating,Sunroof                                                                      1
Name: count, Length: 6199, dtype: int64

In [145]:
cc = df['comfort_convenience'].fillna(df.groupby(['make_model', 'body_type', 'age_years', 'price'])['comfort_convenience'].transform(lambda x: x.mode()[0] if not x.mode().empty else pd.NA))

In [146]:
cc.isna().sum()

np.int64(510)

In [147]:
cc = cc.fillna(df.groupby(['make_model', 'body_type', 'age_years'])['comfort_convenience'].transform(lambda x: x.mode()[0] if not x.mode().empty else pd.NA))

In [148]:
cc.isna().sum()

np.int64(3)

In [149]:
cc = cc.fillna(df.groupby(['make_model', 'body_type'])['comfort_convenience'].transform(lambda x: x.mode()[0] if not x.mode().empty else pd.NA))

In [150]:
cc.isna().sum()

np.int64(0)

In [151]:
df['comfort_convenience'] = cc

### entertainment_media

In [152]:
df['entertainment_media'].value_counts(dropna=False)

entertainment_media
NaN                                                                                                 1374
Bluetooth,Hands-free equipment,On-board computer,Radio,USB                                          1282
Bluetooth,Hands-free equipment,MP3,On-board computer,Radio,USB                                       982
Bluetooth,CD player,Hands-free equipment,MP3,On-board computer,Radio,USB                             783
On-board computer,Radio                                                                              487
                                                                                                    ...
CD player,Hands-free equipment,On-board computer,Radio,Sound system,Television                         1
Digital radio,Hands-free equipment,On-board computer,Radio,Sound system                                1
Digital radio,USB                                                                                      1
CD player,Digital radio,Hands-free equipment,On-board computer,Radio,Sound system,Television,USB       1
Digital radio,MP3,On-board computer,Radio,Sound system,USB                                             1
Name: count, Length: 347, dtype: int64

In [153]:
em = df['entertainment_media'].fillna(df.groupby(['make_model', 'body_type', 'age_years', 'price'])['entertainment_media'].transform(lambda x: x.mode()[0] if not x.mode().empty else pd.NA))

In [154]:
em.isna().sum()

np.int64(780)

In [155]:
em = em.fillna(df.groupby(['make_model', 'body_type', 'age_years'])['entertainment_media'].transform(lambda x: x.mode()[0] if not x.mode().empty else pd.NA))

In [156]:
em.isna().sum()

np.int64(6)

In [157]:
em = em.fillna(df.groupby(['make_model', 'body_type'])['entertainment_media'].transform(lambda x: x.mode()[0] if not x.mode().empty else pd.NA))

In [158]:
em.isna().sum()

np.int64(3)

In [159]:
em = em.fillna(df.groupby(['make_model'])['entertainment_media'].transform(lambda x: x.mode()[0] if not x.mode().empty else pd.NA))

In [160]:
em.isna().sum()

np.int64(0)

In [161]:
df['entertainment_media'] = em

### extras

In [162]:
df['extras'].value_counts(dropna=False)

extras
Alloy wheels                                                                                    3245
NaN                                                                                             2962
Alloy wheels,Touch screen                                                                        697
Alloy wheels,Voice Control                                                                       577
Alloy wheels,Touch screen,Voice Control                                                          541
                                                                                                ...
Alloy wheels,Handicapped enabled,Shift paddles,Sport seats,Touch screen                            1
Alloy wheels,Catalytic Converter,Handicapped enabled,Touch screen,Voice Control,Winter tyres       1
Alloy wheels,Shift paddles,Ski bag,Sport package,Sport suspension,Touch screen,Voice Control       1
Alloy wheels,Handicapped enabled,Roof rack,Touch screen                                            1
Alloy wheels,Shift paddles,Ski bag,Sport seats,Sport suspension,Touch screen,Voice Control         1
Name: count, Length: 660, dtype: int64

In [163]:
e = df['extras'].fillna(df.groupby(['make_model', 'body_type', 'age_years', 'price'])['extras'].transform(lambda x: x.mode()[0] if not x.mode().empty else pd.NA))

In [164]:
e.isna().sum()

np.int64(1598)

In [165]:
e = e.fillna(df.groupby(['make_model', 'body_type', 'age_years'])['extras'].transform(lambda x: x.mode()[0] if not x.mode().empty else pd.NA))

In [166]:
e.isna().sum()

np.int64(16)

In [167]:
e = e.fillna(df.groupby(['make_model', 'body_type'])['extras'].transform(lambda x: x.mode()[0] if not x.mode().empty else pd.NA))

In [168]:
e.isna().sum()

np.int64(11)

In [169]:
e = e.fillna(df.groupby(['make_model'])['extras'].transform(lambda x: x.mode()[0] if not x.mode().empty else pd.NA))

In [170]:
e.isna().sum()

np.int64(0)

In [171]:
df['extras'] = e

### safety_security

In [172]:
df['safety_security'].value_counts(dropna=False)

safety_security
NaN                                                                                                                                                                                                                                                                                                                                                                    982
ABS,Central door lock,Daytime running lights,Driver-side airbag,Electronic stability control,Fog lights,Immobilizer,Isofix,Passenger-side airbag,Power steering,Side airbag,Tire pressure monitoring system,Traction control                                                                                                                                           538
ABS,Central door lock,Daytime running lights,Driver-side airbag,Electronic stability control,Immobilizer,Isofix,Passenger-side airbag,Power steering,Side airbag,Tire pressure monitoring system,Traction control                                                                                                                                                      480
ABS,Central door lock,Daytime running lights,Driver-side airbag,Electronic stability control,Immobilizer,Isofix,Passenger-side airbag,Power steering,Side airbag,Tire pressure monitoring system,Traction control,Xenon headlights                                                                                                                                     275
ABS,Central door lock,Daytime running lights,Driver-side airbag,Electronic stability control,Fog lights,Immobilizer,Isofix,LED Daytime Running Lights,Passenger-side airbag,Power steering,Side airbag,Tire pressure monitoring system,Traction control                                                                                                                272
                                                                                                                                                                                                                                                                                                                                                                      ...
ABS,Adaptive Cruise Control,Blind spot monitor,Driver-side airbag,Electronic stability control,Emergency brake assistant,Fog lights,Head airbag,Isofix,Lane departure warning system,LED Daytime Running Lights,LED Headlights,Passenger-side airbag,Power steering,Side airbag,Tire pressure monitoring system,Traction control,Traffic sign recognition                1
ABS,Adaptive headlights,Blind spot monitor,Central door lock,Daytime running lights,Driver-side airbag,Electronic stability control,Immobilizer,Lane departure warning system,Passenger-side airbag,Power steering,Side airbag,Traction control                                                                                                                          1
ABS,Blind spot monitor,Central door lock,Daytime running lights,Driver-side airbag,Electronic stability control,Emergency brake assistant,Fog lights,Immobilizer,Lane departure warning system,LED Daytime Running Lights,LED Headlights,Passenger-side airbag,Power steering,Side airbag,Tire pressure monitoring system,Traction control,Traffic sign recognition      1
ABS,Adaptive headlights,Central door lock,Daytime running lights,Electronic stability control,Fog lights,Power steering,Traction control                                                                                                                                                                                                                                 1
ABS,Adaptive Cruise Control,Central door lock,Daytime running lights,Driver-side airbag,Electronic stability control,Emergency brake assistant,Fog lights,Immobilizer,Isofix,Lane departure warning system,LED Daytime Running Lights,LED Headlights,Passenger-side airbag,Power steering,Side airbag,Tire pressure monitoring system,Traffic sign recognition           1
Name: count, Length: 4444, dtype: int64

In [173]:
ss = df['safety_security'].fillna(df.groupby(['make_model', 'body_type', 'age_years', 'price'])['safety_security'].transform(lambda x: x.mode()[0] if not x.mode().empty else pd.NA))

In [174]:
ss.isna().sum()

np.int64(539)

In [175]:
ss = ss.fillna(df.groupby(['make_model', 'body_type', 'age_years'])['safety_security'].transform(lambda x: x.mode()[0] if not x.mode().empty else pd.NA))

In [176]:
ss.isna().sum()

np.int64(3)

In [177]:
ss = ss.fillna(df.groupby(['make_model', 'body_type'])['safety_security'].transform(lambda x: x.mode()[0] if not x.mode().empty else pd.NA))

In [178]:
ss.isna().sum()

np.int64(0)

In [179]:
df['safety_security'] = ss

### gears

In [180]:
df['gears'].value_counts(dropna=False)

gears
6.0     5822
NaN     4712
5.0     3239
7.0     1908
8.0      224
9.0        6
1.0        2
3.0        2
4.0        2
2.0        1
50.0       1
Name: count, dtype: int64

In [181]:
df['gearing_type'].value_counts(dropna=False)

gearing_type
Manual            8153
Automatic         7297
Semi-automatic     469
Name: count, dtype: int64

In [182]:
g = df['gears'].fillna(df.groupby(['make_model', 'gearing_type'])['gears'].transform(lambda x: x.mode()[0] if not x.mode().empty else pd.NA))

In [183]:
g.isna().sum()

np.int64(9)

In [184]:
g = g.fillna(df.groupby(['gearing_type'])['gears'].transform(lambda x: x.mode()[0] if not x.mode().empty else pd.NA))

In [185]:
g.isna().sum()

np.int64(0)

In [186]:
df['gears'] = g

### displacement_cc

In [187]:
df['displacement_cc'].value_counts(dropna=False)

displacement_cc
1598.0    4761
999.0     2438
1398.0    1314
1399.0     749
1229.0     677
          ...
890.0        1
1100.0       1
1333.0       1
1580.0       1
1800.0       1
Name: count, Length: 73, dtype: int64

In [188]:
d = df['displacement_cc'].fillna(df.groupby(['make_model', 'fuel', 'cylinders'])['displacement_cc'].transform(lambda x: x.median()))

In [189]:
d.isna().sum()

np.int64(3)

In [190]:
d = d.fillna(df.groupby(['make_model', 'fuel'])['displacement_cc'].transform(lambda x: x.median()))

In [191]:
d.isna().sum()

np.int64(1)

In [192]:
d = d.fillna(df.groupby(['make_model'])['displacement_cc'].transform(lambda x: x.median()))

In [193]:
d.isna().sum()

np.int64(0)

In [194]:
df['displacement_cc'] = d

### hp_kw

In [195]:
df['hp_kw'].value_counts(dropna=False)

hp_kw
85.0     2542
66.0     2122
81.0     1402
100.0    1308
110.0    1112
         ...
195.0       1
123.0       1
4.0         1
163.0       1
115.0       1
Name: count, Length: 81, dtype: int64

In [196]:
df['fuel'].value_counts(dropna=False)

fuel
Benzine     8551
Diesel      7299
LPG/CNG       64
Electric       5
Name: count, dtype: int64

In [197]:
hp = df['hp_kw'].fillna(df.groupby(['make_model', 'fuel', 'displacement_cc'])['hp_kw'].transform(lambda x: x.median()))

In [198]:
hp.isna().sum()

np.int64(13)

In [199]:
hp = hp.fillna(df.groupby(['make_model', 'displacement_cc'])['hp_kw'].transform(lambda x: x.median()))

In [200]:
hp.isna().sum()

np.int64(8)

In [201]:
hp = hp.fillna(df.groupby(['make_model'])['hp_kw'].transform(lambda x: x.median()))

In [202]:
hp.isna().sum()

np.int64(0)

In [203]:
df['hp_kw'] = hp

### warranty_months

In [204]:
df['warranty_months'].value_counts(dropna=False)

warranty_months
NaN     11066
12.0     2594
24.0     1118
60.0      401
36.0      279
48.0      149
6.0       125
72.0       59
3.0        33
23.0       11
18.0       10
20.0        7
25.0        6
2.0         5
50.0        4
26.0        4
16.0        4
13.0        3
19.0        3
1.0         3
4.0         3
34.0        3
46.0        2
22.0        2
28.0        2
11.0        2
17.0        2
45.0        2
14.0        2
9.0         2
21.0        2
47.0        1
49.0        1
56.0        1
10.0        1
8.0         1
7.0         1
15.0        1
65.0        1
33.0        1
40.0        1
30.0        1
Name: count, dtype: int64

In [205]:
df.loc[df['warranty_months'].isna(), ['condition', 'age_years']].value_counts(dropna=False)

condition       age_years
Used            3.0          2465
                1.0          2328
                2.0          2068
New             0.0          1320
Pre-registered  0.0           859
Employee's car  1.0           579
Used            0.0           514
Demonstration   0.0           482
Pre-registered  1.0           140
Demonstration   1.0           110
Employee's car  0.0           101
                2.0            65
Demonstration   2.0            21
Employee's car  3.0             6
Pre-registered  2.0             5
New             1.0             2
Demonstration   3.0             1
Name: count, dtype: int64

With older used vehicles being most frequent, likely no longer under warranty

In [206]:
df['warranty_months'] = df['warranty_months'].fillna(0)

### upholstery_type

In [207]:
df['upholstery_type'].value_counts(dropna=False)

upholstery_type
Cloth           8423
NaN             4871
Part leather    1499
Full leather    1009
Velour            60
alcantara         57
Name: count, dtype: int64

In [208]:
ut = df['upholstery_type'].fillna(df.groupby(['make_model', 'body_type', 'price'])['upholstery_type'].transform(lambda x: x.mode()[0] if not x.mode().empty else pd.NA))

In [209]:
ut.isna().sum()

np.int64(2043)

In [210]:
ut = ut.fillna(df.groupby(['make_model', 'body_type'])['upholstery_type'].transform(lambda x: x.mode()[0] if not x.mode().empty else pd.NA))

In [211]:
ut.isna().sum()

np.int64(9)

In [212]:
ut = ut.fillna(df.groupby(['make_model'])['upholstery_type'].transform(lambda x: x.mode()[0] if not x.mode().empty else pd.NA))

In [213]:
ut.isna().sum()

np.int64(0)

In [214]:
df['upholstery_type'] = ut

### upholstery_color

In [215]:
df['upholstery_color'].value_counts(dropna=False)

upholstery_color
Black     7710
NaN       6821
Grey      1103
Brown      195
Beige       51
Blue        14
White       11
Red          9
Yellow       4
Orange       1
Name: count, dtype: int64

In [216]:
uc = df['upholstery_color'].fillna(df.groupby(['make_model', 'upholstery_type'])['upholstery_color'].transform(lambda x: x.mode()[0] if not x.mode().empty else pd.NA))

In [217]:
uc.isna().sum()

np.int64(0)

In [218]:
df['upholstery_color'] = uc

### weight_kg

In [219]:
df['weight_kg'].value_counts(dropna=False)

weight_kg
NaN       6974
1163.0     574
1360.0     356
1165.0     301
1335.0     242
          ...
1780.0       1
1797.0       1
1939.0       1
1847.0       1
2037.0       1
Name: count, Length: 435, dtype: int64

In [220]:
w = df['weight_kg'].fillna(df.groupby(['make_model', 'body_type', 'nr_of_doors'])['weight_kg'].transform(lambda x: x.median()))

In [221]:
w.isna().sum()

np.int64(338)

In [222]:
w = w.fillna(df.groupby(['make_model', 'body_type'])['weight_kg'].transform(lambda x: x.median()))

In [223]:
w.isna().sum()

np.int64(43)

In [224]:
w = w.fillna(df.groupby(['make_model'])['weight_kg'].transform(lambda x: x.median()))

In [225]:
w.isna().sum()

np.int64(35)

In [226]:
w = w.fillna(df.groupby(['body_type'])['weight_kg'].transform(lambda x: x.median()))

In [227]:
w.isna().sum()

np.int64(0)

In [228]:
df['weight_kg'] = w

### city_l_per_100km

In [229]:
df['city_l_per_100km'].value_counts(dropna=False)

city_l_per_100km
NaN     2436
5.0      669
5.8      633
4.5      580
4.3      533
        ...
10.4       1
66.0       1
16.1       1
64.0       1
9.7        1
Name: count, Length: 87, dtype: int64

In [230]:
electric_mask = df['fuel'].str.contains('Electric', case=False, na=False)
df.loc[electric_mask, 'city_l_per_100km'] = 0.0

In [231]:
city = df['city_l_per_100km'].fillna(df.groupby(['make_model', 'fuel', 'displacement_cc', 'age_years'])['city_l_per_100km'].transform(lambda x: x.median()))

In [232]:
city.isna().sum()

np.int64(208)

In [233]:
city = city.fillna(df.groupby(['make_model', 'fuel', 'displacement_cc'])['city_l_per_100km'].transform(lambda x: x.median()))

In [234]:
city.isna().sum()

np.int64(82)

In [235]:
city = city.fillna(df.groupby(['make_model', 'fuel'])['city_l_per_100km'].transform(lambda x: x.median()))

In [236]:
city.isna().sum()

np.int64(0)

In [237]:
city = city.fillna(df.groupby(['fuel'])['city_l_per_100km'].transform(lambda x: x.median()))

In [238]:
city.isna().sum()

np.int64(0)

In [239]:
city = city.fillna(df.groupby(['make_model'])['city_l_per_100km'].transform(lambda x: x.median()))

In [240]:
city.isna().sum()

np.int64(0)

In [241]:
df['city_l_per_100km'] = city

### country_l_per_100km

In [242]:
df['country_l_per_100km'].value_counts(dropna=False)

country_l_per_100km
NaN     2376
4.2     1178
3.7     1089
4.4      898
4.5      848
3.8      802
3.9      777
4.7      615
4.1      592
4.0      589
3.5      525
4.3      520
4.6      516
3.6      486
3.1      481
4.9      481
3.3      457
3.4      353
4.8      341
5.3      278
5.4      239
5.1      232
5.7      204
3.2      180
5.6      154
3.0      142
5.0      130
5.2      117
6.3       52
6.0       42
5.5       36
10.0      32
5.8       30
7.7       20
6.6       19
2.9       16
6.4       15
2.8        9
0.0        9
44.0       4
6.5        4
7.3        4
7.0        3
7.1        3
6.7        2
37.0       2
35.0       2
6.9        2
6.1        2
5.9        2
7.8        2
10.3       1
2.0        1
8.0        1
8.6        1
7.6        1
42.0       1
1.0        1
Name: count, dtype: int64

In [243]:
electric_mask = df['fuel'].str.contains('Electric', case=False, na=False)
df.loc[electric_mask, 'country_l_per_100km'] = 0.0

In [244]:
country = df['country_l_per_100km'].fillna(df.groupby(['make_model', 'fuel', 'displacement_cc', 'age_years'])['country_l_per_100km'].transform(lambda x: x.median()))

In [245]:
country.isna().sum()

np.int64(201)

In [246]:
country = country.fillna(df.groupby(['make_model', 'fuel', 'displacement_cc'])['country_l_per_100km'].transform(lambda x: x.median()))

In [247]:
country.isna().sum()

np.int64(82)

In [248]:
country = country.fillna(df.groupby(['make_model', 'fuel'])['country_l_per_100km'].transform(lambda x: x.median()))

In [249]:
country.isna().sum()

np.int64(0)

In [250]:
country = country.fillna(df.groupby(['fuel'])['country_l_per_100km'].transform(lambda x: x.median()))

In [251]:
country.isna().sum()

np.int64(0)

In [252]:
country = country.fillna(df.groupby(['make_model'])['country_l_per_100km'].transform(lambda x: x.median()))

In [253]:
country.isna().sum()

np.int64(0)

In [254]:
df['country_l_per_100km'] = country

### combined_l_per_100km

In [255]:
df['combined_l_per_100km'].value_counts(dropna=False)

combined_l_per_100km
NaN     2033
5.4      770
3.9      733
4.0      713
5.1      657
        ...
32.0       1
33.0       1
50.0       1
1.0        1
46.0       1
Name: count, Length: 73, dtype: int64

In [256]:
electric_mask = df['fuel'].str.contains('Electric', case=False, na=False)
df.loc[electric_mask, 'combined_l_per_100km'] = 0.0

In [257]:
comb = df['combined_l_per_100km'].fillna((df['city_l_per_100km'] + df['country_l_per_100km'])/2)

In [258]:
comb.isna().sum()

np.int64(0)

In [259]:
comb.value_counts(dropna=False)

combined_l_per_100km
5.40     807
3.90     751
4.00     721
5.10     661
5.60     660
        ...
33.00      1
50.00      1
6.55       1
46.00      1
6.75       1
Name: count, Length: 141, dtype: int64

In [260]:
df['combined_l_per_100km'] = comb

### emissions_g_co2/km

In [261]:
df['emissions_g_co2/km'].value_counts(dropna=False)

emissions_g_co2/km
NaN      2436
120.0     740
99.0      545
97.0      537
104.0     501
         ...
180.0       1
45.0        1
171.0       1
183.0       1
193.0       1
Name: count, Length: 120, dtype: int64

In [262]:
electric_mask = df['fuel'].str.contains('Electric', case=False, na=False)
df.loc[electric_mask, 'emissions_g_co2/km'] = 0.0

In [263]:
eco2 = df['emissions_g_co2/km'].fillna(df.groupby(['make_model', 'fuel', 'displacement_cc', 'age_years'])['emissions_g_co2/km'].transform(lambda x: x.median()))

In [264]:
eco2.isna().sum()

np.int64(194)

In [265]:
eco2 = eco2.fillna(df.groupby(['make_model', 'fuel', 'displacement_cc'])['emissions_g_co2/km'].transform(lambda x: x.median()))

In [266]:
eco2.isna().sum()

np.int64(88)

In [267]:
eco2 = eco2.fillna(df.groupby(['make_model', 'fuel'])['emissions_g_co2/km'].transform(lambda x: x.median()))

In [268]:
eco2.isna().sum()

np.int64(1)

In [269]:
eco2 = eco2.fillna(df.groupby(['make_model'])['emissions_g_co2/km'].transform(lambda x: x.median()))

In [270]:
eco2.isna().sum()

np.int64(1)

In [271]:
eco2 = eco2.fillna(df.groupby(['fuel'])['emissions_g_co2/km'].transform(lambda x: x.median()))

In [272]:
eco2.isna().sum()

np.int64(0)

In [273]:
df['emissions_g_co2/km'] = eco2

## Export Data

In [274]:
missing_df = df.isnull().sum().reset_index()
missing_df.columns = ['column', 'missing_count']
missing_df = missing_df[missing_df['missing_count'] > 0].reset_index(drop=True)
print(missing_df)

Empty DataFrame
Columns: [column, missing_count]
Index: []

In [275]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15919 entries, 0 to 15918
Data columns (total 34 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   make_model            15919 non-null  str
 1   body_type             15919 non-null  str
 2   price                 15919 non-null  int64
 3   vat                   15919 non-null  str
 4   km                    15919 non-null  float64
 5   previous_owners       15919 non-null  float64
 6   next_inspection       15919 non-null  period[M]
 7   inspection_new        15919 non-null  str
 8   body_color            15919 non-null  str
 9   paint_type            15919 non-null  str
 10  nr_of_doors           15919 non-null  float64
 11  nr_of_seats           15919 non-null  object
 12  gearing_type          15919 non-null  str
 13  cylinders             15919 non-null  object
 14  drive_chain           15919 non-null  str
 15  fuel                  15919 non-null  str
 16  emission_class        15919 non-null  str
 17  comfort_convenience   15919 non-null  str
 18  entertainment_media   15919 non-null  str
 19  extras                15919 non-null  str
 20  safety_security       15919 non-null  str
 21  gears                 15919 non-null  object
 22  displacement_cc       15919 non-null  float64
 23  age_years             15919 non-null  float64
 24  hp_kw                 15919 non-null  float64
 25  condition             15919 non-null  str
 26  warranty_months       15919 non-null  float64
 27  upholstery_type       15919 non-null  str
 28  upholstery_color      15919 non-null  str
 29  weight_kg             15919 non-null  float64
 30  combined_l_per_100km  15919 non-null  float64
 31  city_l_per_100km      15919 non-null  float64
 32  country_l_per_100km   15919 non-null  float64
 33  emissions_g_co2/km    15919 non-null  float64
dtypes: float64(12), int64(1), object(3), period[M](1), str(17)
memory usage: 4.1+ MB

In [276]:
df.to_csv('data/phase2_cleaned_data.csv', index=False)